server:
  port: 8000   #default 는 8080
  servlet:
    context-path: /blog   #default 는 /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
 
# 아무 설정을 안한경우 기본경로 : src/main/resources/static  
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul #blog 는 스키마명 
    username: root
    password: 111111
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update 	#none, update, create 선택 가능 (최초에면 create하고 update로 바꿔놔야 기존의 데이터들이 안지워진)
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # Entity(테이블)을 만들때 변수명 그대로 테이블을 만들어준다 // 다른전략도 있다.
      use-new-id-generator-mappings: false #jpa가 사용하는 기본 넘버링 전략을 따라가지 않는다 true면 따라간다 
    show-sql: true # 콘솔창에 보여줌 
    properties:
      hibernate.format_sql: true # 콘솔창에 예쁘게 보여

  jackson:
    serialization:
      fail-on-empty-beans: false
      
    # application.yml 로 파일이름 수정 (yml은 json과 비슷한 방식)
    # property 방식은 불편함!!
    # 예전엔 web, server xml 등에서 설정했지 이젠 여기서 모든 spring 설정을 할 수 있음 
    